import type { AxisInfo } from "./types";

export const AXES: AxisInfo[] = [
  {
    key: "per",
    label: "PER",
    description: "주가수익비율",
    domain: [0, 50],
    inverted: false, // lower is better
  },
  {
    key: "pbr",
    label: "PBR",
    description: "주가순자산비율",
    domain: [0, 10],
    inverted: false, // lower is better
  },
  {
    key: "roe",
    label: "ROE",
    description: "자기자본이익률",
    domain: [0, 30],
    inverted: true, // higher is better
  },
  {
    key: "debtRatio",
    label: "부채비율",
    description: "총부채/자기자본",
    domain: [0, 200],
    inverted: false, // lower is better
  },
  {
    key: "divYield",
    label: "배당수익률",
    description: "주당배당금/주가",
    domain: [0, 10],
    inverted: true, // higher is better
  },
];

// Sample stock data for the parallel coordinates chart
export const SAMPLE_STOCKS = [
  {
    id: "1",
    name: "삼성전자",
    sector: "반도체",
    per: 12.5,
    pbr: 1.2,
    roe: 15.3,
    debtRatio: 35,
    divYield: 2.1,
  },
  {
    id: "2",
    name: "SK하이닉스",
    sector: "반도체",
    per: 8.2,
    pbr: 1.5,
    roe: 18.7,
    debtRatio: 45,
    divYield: 1.5,
  },
  {
    id: "3",
    name: "LG에너지솔루션",
    sector: "2차전지",
    per: 45.3,
    pbr: 4.2,
    roe: 8.5,
    debtRatio: 60,
    divYield: 0.5,
  },
  {
    id: "4",
    name: "현대자동차",
    sector: "자동차",
    per: 5.8,
    pbr: 0.6,
    roe: 12.1,
    debtRatio: 120,
    divYield: 3.5,
  },
  {
    id: "5",
    name: "기아",
    sector: "자동차",
    per: 4.5,
    pbr: 0.8,
    roe: 18.2,
    debtRatio: 95,
    divYield: 4.2,
  },
  {
    id: "6",
    name: "POSCO홀딩스",
    sector: "철강",
    per: 7.2,
    pbr: 0.5,
    roe: 8.9,
    debtRatio: 55,
    divYield: 5.1,
  },
  {
    id: "7",
    name: "네이버",
    sector: "IT서비스",
    per: 25.6,
    pbr: 1.8,
    roe: 7.2,
    debtRatio: 25,
    divYield: 0.8,
  },
  {
    id: "8",
    name: "카카오",
    sector: "IT서비스",
    per: 35.2,
    pbr: 2.1,
    roe: 5.8,
    debtRatio: 40,
    divYield: 0.3,
  },
  {
    id: "9",
    name: "셀트리온",
    sector: "바이오",
    per: 42.1,
    pbr: 3.5,
    roe: 9.2,
    debtRatio: 30,
    divYield: 0.6,
  },
  {
    id: "10",
    name: "삼성바이오로직스",
    sector: "바이오",
    per: 65.3,
    pbr: 5.8,
    roe: 12.5,
    debtRatio: 20,
    divYield: 0.2,
  },
  {
    id: "11",
    name: "KB금융",
    sector: "금융",
    per: 5.2,
    pbr: 0.45,
    roe: 9.8,
    debtRatio: 180,
    divYield: 6.2,
  },
  {
    id: "12",
    name: "신한지주",
    sector: "금융",
    per: 4.8,
    pbr: 0.42,
    roe: 10.2,
    debtRatio: 175,
    divYield: 5.8,
  },
  {
    id: "13",
    name: "하나금융지주",
    sector: "금융",
    per: 4.2,
    pbr: 0.38,
    roe: 11.5,
    debtRatio: 185,
    divYield: 6.5,
  },
  {
    id: "14",
    name: "LG화학",
    sector: "화학",
    per: 18.5,
    pbr: 1.1,
    roe: 6.5,
    debtRatio: 75,
    divYield: 1.8,
  },
  {
    id: "15",
    name: "한화솔루션",
    sector: "화학",
    per: 22.3,
    pbr: 0.9,
    roe: 4.2,
    debtRatio: 110,
    divYield: 1.2,
  },
  {
    id: "16",
    name: "에코프로비엠",
    sector: "2차전지",
    per: 85.2,
    pbr: 8.5,
    roe: 22.3,
    debtRatio: 85,
    divYield: 0.1,
  },
  {
    id: "17",
    name: "포스코퓨처엠",
    sector: "2차전지",
    per: 55.8,
    pbr: 5.2,
    roe: 15.8,
    debtRatio: 70,
    divYield: 0.3,
  },
  {
    id: "18",
    name: "현대모비스",
    sector: "자동차부품",
    per: 6.5,
    pbr: 0.55,
    roe: 8.5,
    debtRatio: 65,
    divYield: 3.8,
  },
  {
    id: "19",
    name: "삼성SDI",
    sector: "2차전지",
    per: 28.5,
    pbr: 2.2,
    roe: 10.5,
    debtRatio: 50,
    divYield: 0.8,
  },
  {
    id: "20",
    name: "LG전자",
    sector: "가전",
    per: 15.2,
    pbr: 0.85,
    roe: 6.8,
    debtRatio: 130,
    divYield: 1.5,
  },
];
